name: Rust
on:
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
